dist: trusty
sudo: false
language: node_js
node_js: node

install:
  - npm ci
cache:
  directories:
    - $HOME/.npm
script:
  - npm run lint:numeric-input
  - npm run build:numeric-input
  - npm run lint:delayed-dragover
  - npm run build:delayed-dragover
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/ng-dl
  on:
    branch: master

git:
  depth: 3

after_success:
  - npm run travis-deploy-once "npm run semantic-release -e semantic-release-monorepo"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
